apiVersion: v1
kind: ConfigMap
metadata:
  name: mencare-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: mysql
  DB_NAME: {{ .Values.mysql.database }}
  DB_PORT: "{{ .Values.mysql.port }}"